scenes:
  library_map:
    world_usd: assets/worlds/library/library_environment.usd
    tray_usd: assets/props/tray/tray_set.usd
    nav_map_yaml: ../ros2_ws/src/shelving_navigation/maps/library_map.yaml

    robot:
      usd: assets/robots/franka_nav.usda
      prim_path: /World/ridgeback_franka

      simulation_pose:
        position: [-6.086313, 5.546779, 0.0]
        yaw: 0.0
        
    ros:
      domain_id: 130
      namespace: ""
